language: java
#skip installation step
install: true

script:
  - if [ "$WITH_COVERALLS" == "true" ];
    then
      mvn -f com.example.myproject/pom.xml clean verify -Pjacoco
      coveralls:report;
  else
    mvn -f com.example.myproject/pom.xml clean verify;
    fi

jdk:
- oraclejdk8
- oraclejdk7
- openjdk6

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env: WITH_COVERALLS=true
    - jdk: oraclejdk7
    - jdk: openjdk6
    - os: osx
      osx_image: xcode8